Messages:
ClanSettings:
  #Эта регулярное выражение которому должны соответствовать все id кланов;
  #Если не разбираетесь в регулярных выражениях лучше не трогать его
  #Стандарт:
  #Можно использовать все латинские буквы
  #Можно использовать числа от 0 до 9
  #Длинна id должна быть 4 символа
  IdRegex: "^[A-Za-z][A-Za-z0-9]{3}$"
  #Цена создания клана
  CreateMoney: 150000
  #Цена установки/изменения цвета тега
  ColorMoney: 15000
  #Цена установки/изменения клановой базы
  HomeMoney: 15000
DataProviderSettings:
  MySql:
    Enable: false
    UserName: "UserName"
    DataBaseName: "DataBaseName"
    IP: "IP"
    Password: "Password"
    #В тиках
    UpdateTime: 1200